language: node_js
node_js:
  - "6.9"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install :
  - npm i
  - cd mobile && npm i && cd -
script :
  - npm test
  - npm run lint
  - npm run prod
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
notifications:
  email: false
