language: node_js
node_js:
  - "6"
before_install:
  - cp ./server/config.sample.json ./server/config.json
install :
  - npm i
  - cd mobile && npm i && cd -
script :
  - npm test
  - npm run lint
  - npm run prod
after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
notifications:
  email: false
