export const placeholderImage =
  'data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD//gATQ3JlYXRlZCB3aXRoIEdJTVD/' +
  '2wBDAAMCAgMCAgMDAwMEAwMEBQgFBQQEBQoHBwYIDAoMDAsKCwsNDhIQDQ4RDgsLEBYQERMUFRUVDA8XGBYUGBIUFRT/' +
  '2wBDAQMEBAUEBQkFBQkUDQsNFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBT/' +
  'wgARCAABAu4DAREAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAj/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/' +
  '9oADAMBAAIQAxAAAAGqQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/8QAFBABAAAAAAAAAAAAA' +
  'AAAAAAAYP/aAAgBAQABBQI9/8QAFBEBAAAAAAAAAAAAAAAAAAAAYP/aAAgBAwEBPwE9/8QAFBEBAAAAAAAAAAAAA' +
  'AAAAAAAYP/aAAgBAgEBPwE9/8QAFBABAAAAAAAAAAAAAAAAAAAAYP/aAAgBAQAGPwI9/8QAFBABAAAAAAAAAAAAA' +
  'AAAAAAAYP/aAAgBAQABPyE9/9oADAMBAAIAAwAAABCSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS' +
  'T//xAAUEQEAAAAAAAAAAAAAAAAAAABg/9oACAEDAQE/ED3/xAAUEQEAAAAAAAAAAAAAAAAAAABg/9oACAECAQE/E' +
  'D3/xAAUEAEAAAAAAAAAAAAAAAAAAABg/9oACAEBAAE/ED3/2Q==';
